import unittest
from src.dependency_searchers.package_parsers import MakeFileParser


class TestMarkDownParser(unittest.TestCase):

    def test_parse_valid_mk_file(self):
        makefile_data_valid_file = """################################################################################
#
# tpm2-tools
#
################################################################################

TPM2_TOOLS_VERSION = 1.1.0
TPM2_TOOLS_SITE = https://github.com/tpm2-software
TPM2_TOOLS_LICENSE = BSD-3-Clause
TPM2_TOOLS_LICENSE_FILES = copy
TPM2_TOOLS_DEPENDENCIES = libcurl

$(eval $(autotools-package))"""

        dependencies = MakeFileParser().parse(makefile_data_valid_file)
        self.assertEqual(len(dependencies), 1)
        self.assertEqual(dependencies[0]['ModuleName'], 'tpm2_tools')
        self.assertEqual(dependencies[0]['Version'], '1.1.0')
        self.assertEqual(dependencies[0]['License'], 'BSD-3-Clause')

    def test_parse_invalid_mk_file(self):
        makefile_data_invalid_data = """################################################################################
#
# ifupdown-scripts
#
################################################################################

define IFUPDOWN_SCRIPTS_PREAMBLE
	echo "# interface file auto-generated by the cpu" \
		> $(TARGET_DIR)network/interfaces
endef
$(eval $(generic-package))

"""

        dependencies = MakeFileParser().parse(makefile_data_invalid_data)
        self.assertEqual(len(dependencies), 0)

    def test_parse_with_new_line_deliminator(self):
        make_file_with_new_line_delimiter = """################################################################################
#
# ffmpeg
#
################################################################################

FFMPEG_VERSION = \
4.4.1
FFMPEG_SOURCE = ffmpeg-$(FFMPEG_VERSION).tar.xz
FFMPEG_SITE = http://ffmpeg.org/releases
FFMPEG_INSTALL_STAGING = YES
FFMPEG_LICENSE = \
LGPL-2.1+, libjpeg license
FFMPEG_LICENSE_FILES = LICENSE.md COPYING.LGPLv2.1
ifeq ($(BR2_PACKAGE_FFMPEG_GPL),y)
FFMPEG_LICENSE_FILES += COPYING.GPLv2
endif

FFMPEG_CPE_ID_VENDOR = ffmpeg"""

        dependencies = MakeFileParser().parse(make_file_with_new_line_delimiter)
        self.assertEqual(dependencies[0]['ModuleName'], 'ffmpeg')
        self.assertEqual(dependencies[0]['Version'], '4.4.1')
        self.assertEqual(dependencies[0]['License'], 'LGPL-2.1+, libjpeg license')

    def test_parse_dependencies_unknown_license(self):
        makefile_missing_license_data = """################################################################################
#
# can-utils
#
################################################################################

CAN_UTILS_VERSION = 1.1.0
CAN_UTILS_SITE = $(call github,linux-can,can-utils)
CAN_UTILS_AUTORECONF = YES

$(eval $(autotools-package))
"""

        dependencies = MakeFileParser().parse(makefile_missing_license_data)
        self.assertEqual(dependencies[0]['ModuleName'], 'can_utils')
        self.assertEqual(dependencies[0]['Version'], '1.1.0')
        self.assertEqual(dependencies[0]['License'], 'N/A')

